Gemelnet csv dump
hasadna/open-pension-net-scraper pull request #5
Opened 2016-11-17 23:27 UTC by thedod

Dump a single month of a single kupa from gemelnet. (#3)
[Example spreadsheet](https://gist.github.com/anonymous/ee0b466abbb5a00c2572e4d068b94255).

2016-11-19 18:18 UTC, nirgn975 requested changes

2016-11-19 18:18 UTC, nirgn975 commented on requirements.txt
> +pkg-resources==0.0.0
I think it's come with setup tools. Do you even can install it like this?

2016-11-19 18:18 UTC, nirgn975 commented on README.md
> +# Open Pension Scraper
Re-roll from master and this should disappear (this isn't a change from this commit).

2016-11-19 18:18 UTC, nirgn975 commented on .travis.yml
> +sudo: required
Re-roll from master and this file should disappear (this file isn't a change from this commit).

2016-11-19 18:18 UTC, nirgn975 commented on .gitignore
> +data/*.csv
Re-roll from master and this file should disappear (this file isn't a change from this commit).

2016-11-19 18:18 UTC, nirgn975 commented on web_sources/gemelnet.py
> +def save_csv_monthly_portfolio(kupa_id, year, month):
Please add  a little docstring to the function.

2016-11-19 18:18 UTC, nirgn975 commented on web_sources/gemelnet.py
> +    period = '{:04d}{:02d}'.format(year, month)
Please add  a little docstring to the function.

2016-11-19 18:18 UTC, nirgn975 commented on web_sources/gemelnet.py
> +    return [
Please add  a little docstring to the function.

2016-11-19 18:18 UTC, nirgn975 commented on web_sources/gemelnet.py
> +    import argparse
`import` statement should be at the top of the file.

2016-11-19 21:01 UTC, thedod commented on requirements.txt
> +pkg-resources==0.0.0
I have no idea where it came from, but things work well when I remove this line, so I will :wink:

2016-11-19 22:16 UTC, thedod commented on .gitignore
> +data/*.csv
There's a small change: `data/*.csv` are created by `gemelnet.py` (added at this PR).

2016-11-20 06:01 UTC, nirgn975 requested changes

2016-11-20 06:01 UTC, nirgn975 commented on .gitignore
> +data/*.csv
So just delete those changes, and add it to the end of the `.gitignore` file, under `### Custom ###` (if we don't have that section in the file, add it at the end).

2016-11-20 06:01 UTC, nirgn975 commented on README.md
> +```
Add shell to the code block, like:
```
```shell
```

2016-11-20 07:41 UTC, nirgn975 approved these changes

2016-11-20 07:41 UTC, merged